use crate::error::RyndResult;
use crate::syntax::ast::*;
use crate::vm::runtime::pattern_names;

/// Emits direct Rust expressions and closures, with shared value semantics.
/// Generated programs do not contain a parser, bytecode compiler, or VM loop.
#[derive(Default)]
pub struct RustTranspiler {
    bindings: Vec<(String, String)>,
    depth: usize,
    counter: usize,
}
impl RustTranspiler {
    pub fn new() -> Self {
        Self::default()
    }
    fn fresh(&mut self) -> String {
        let id = self.counter;
        self.counter += 1;
        format!("__v{id}")
    }
    pub fn transpile(&mut self, program: &Program) -> RyndResult<String> {
        // Apply the same compile-time validation on both execution paths.
        crate::vm::compiler::Compiler::new().compile(program)?;
        *self = Self::new();
        let mut out = String::from(
            "// Generated by Rynd: standalone Rust with a shared dynamic value runtime.\n#![allow(dead_code, unused_imports, unused_variables, unused_mut, unreachable_code)]\n",
        );
        out.push_str("mod error {\n");
        out.push_str(include_str!("../error.rs"));
        out.push_str("\n}\nmod syntax { pub mod ast {\n");
        out.push_str(include_str!("../syntax/ast.rs"));
        out.push_str("\n}}\nmod vm { pub mod value {\n");
        out.push_str(include_str!("../vm/value.rs"));
        out.push_str("\n} pub mod runtime {\n");
        out.push_str(include_str!("../vm/runtime.rs"));
        out.push_str("\n} pub mod json {\n");
        out.push_str(include_str!("../vm/json.rs"));
        out.push_str("\n} pub mod scripting {\n");
        out.push_str(include_str!("../vm/scripting.rs"));
        out.push_str("\n} pub mod collections {\n");
        out.push_str(include_str!("../vm/collections.rs"));
        out.push_str("\n}}\n");
        out.push_str("use error::{RyndResult, Span};\nuse syntax::ast::{Pattern, Literal, BinaryOp, UnaryOp};\nuse vm::value::Value;\nuse vm::runtime::{self, Runtime};\nuse std::rc::Rc;\nfn rynd_program(__rt: &mut dyn Runtime) -> RyndResult<Value> {\n");
        out.push_str(&self.program_body(program)?);
        out.push_str("Ok(Value::Nil)\n}\nfn main() {\nlet mut rt = runtime::NativeRuntime::default();\nrt.set_global(\"args\", Value::list(std::env::args().skip(1).map(Value::string).collect()));\nmatch rynd_program(&mut rt) {\nOk(value) => { if value != Value::Nil { println!(\"{}\", value); } },\nErr(error) => { eprintln!(\"Execution Error: {}\", error); std::process::exit(1); }\n}\n}\n");
        Ok(out)
    }
    /// Emit a Cargo module using the public Rynd runtime types.
    pub fn transpile_module(
        &mut self,
        program: &Program,
        exports: &[String],
    ) -> RyndResult<String> {
        crate::vm::compiler::Compiler::new().compile(program)?;
        *self = Self::new();
        let mut out = String::from(
            "use rynd::{RyndResult, Span, Value};\nuse rynd::syntax::ast::{Pattern, Literal, BinaryOp, UnaryOp};\nuse rynd::vm::runtime::{self, Runtime};\nuse std::rc::Rc;\n",
        );
        out.push_str(&format!("pub const EXPORTS: &[&str] = &{:?};\n", exports));
        out.push_str("pub fn init(__rt: &mut dyn Runtime) -> RyndResult<Value> {\n");
        out.push_str(&self.program_body(program)?);
        out.push_str("Ok(Value::Nil)\n}\n");
        Ok(out)
    }
    fn program_body(&mut self, program: &Program) -> RyndResult<String> {
        let mut out = String::new();
        for (i, stmt) in program.statements.iter().enumerate() {
            if i + 1 == program.statements.len()
                && let Stmt::Expression(expr) = stmt
            {
                out.push_str(&format!(
                    "return Ok({});\n",
                    self.transpile_expression(expr)?
                ));
                continue;
            }
            out.push_str(&self.statement(stmt)?);
        }
        Ok(out)
    }
    fn checked(&self, expr: &Expr, code: String) -> String {
        format!("({code}).map_err(|e| e.at({}))?", span_code(&expr.span))
    }
    fn bind_names(&mut self, names: Vec<String>, values: &str) -> String {
        let mut code = String::new();
        for (i, name) in names.into_iter().enumerate() {
            if self.depth == 0 {
                code.push_str(&format!(
                    "__rt.set_global({name:?}, {values}[{i}].clone());\n"
                ));
            } else {
                let rust = self.fresh();
                code.push_str(&format!("let {rust} = {values}[{i}].clone();\n"));
                self.bindings.push((name, rust));
            }
        }
        code
    }
    fn statement(&mut self, stmt: &Stmt) -> RyndResult<String> {
        Ok(match stmt {
            Stmt::Public(inner) => self.statement(inner)?,
            Stmt::Import { .. } => {
                return Err(crate::error::RyndError::TranspileError {
                    message: "Unresolved import; load the module graph before generating Rust"
                        .into(),
                });
            }
            Stmt::Let {
                pattern,
                init,
                span,
                ..
            } => {
                let value = self.transpile_expression(init)?;
                let bindings = self.fresh();
                let mut code = format!(
                    "let {bindings} = runtime::match_pattern(&{}, &({value})).ok_or_else(|| runtime::error(\"Pattern does not match value\").at({}))?;\n",
                    pattern_code(pattern),
                    span_code(span)
                );
                code.push_str(&self.bind_names(pattern_names(pattern), &bindings));
                code
            }
            Stmt::Function {
                name, params, body, ..
            } => {
                let value = self.function(name, params, body)?;
                let tmp = self.fresh();
                let mut code = format!("let {tmp} = vec![{value}];\n");
                code.push_str(&self.bind_names(vec![name.clone()], &tmp));
                code
            }
            Stmt::Expression(expr) => format!("{};\n", self.transpile_expression(expr)?),
            Stmt::Return { value, .. } => format!(
                "return Ok({});\n",
                if let Some(v) = value {
                    self.transpile_expression(v)?
                } else {
                    "Value::Nil".into()
                }
            ),
        })
    }
    fn function(&mut self, name: &str, params: &[String], body: &Expr) -> RyndResult<String> {
        let old_bindings = std::mem::take(&mut self.bindings);
        let old_depth = self.depth;
        let mut captures = String::new();
        let mut needed = crate::syntax::captures::free_names(name, params, body);
        for (name, rust) in old_bindings.iter().rev() {
            if !needed.remove(name) {
                continue;
            }
            let capture = self.fresh();
            captures.push_str(&format!("let {capture} = {rust}.clone();\n"));
            self.bindings.push((name.clone(), capture));
        }
        self.depth = 1;
        let self_var = self.fresh();
        self.bindings.push((name.into(), self_var.clone()));
        let mut setup = format!("let {self_var} = __self.clone();\n");
        for (i, param) in params.iter().enumerate() {
            let rust = self.fresh();
            setup.push_str(&format!("let {rust} = __args[{i}].clone();\n"));
            self.bindings.push((param.clone(), rust));
        }
        let body = self.transpile_expression(body)?;
        self.bindings = old_bindings;
        self.depth = old_depth;
        Ok(format!(
            "{{ {captures} Value::Compiled {{ name: {name:?}.into(), arity: {}, func: Rc::new(move |__rt, __args, __self| {{ {setup} Ok({body}) }}) }} }}",
            params.len()
        ))
    }
    fn call(&mut self, expr: &Expr, callee: &Expr, args: &[&Expr]) -> RyndResult<String> {
        let callee = self.transpile_expression(callee)?;
        let args = args
            .iter()
            .map(|a| self.transpile_expression(a))
            .collect::<RyndResult<Vec<_>>>()?
            .join(", ");
        let f = self.fresh();
        let a = self.fresh();
        Ok(format!(
            "{{ let {f} = {callee}; let {a} = [{args}]; {} }}",
            self.checked(expr, format!("__rt.call_ref(&{f}, &{a})"))
        ))
    }
    pub fn transpile_expression(&mut self, expr: &Expr) -> RyndResult<String> {
        if let Some(lowered) = lower_comprehension(expr) {
            return self.transpile_expression(&lowered);
        }
        Ok(match &expr.kind {
            ExprKind::Literal(lit) => format!("runtime::literal(&{})", literal_code(lit)),
            ExprKind::Identifier(name) => {
                if let Some((_, rust)) = self.bindings.iter().rev().find(|(n, _)| n == name) {
                    format!("{rust}.clone()")
                } else {
                    self.checked(expr, format!("__rt.get_global({name:?})"))
                }
            }
            ExprKind::Binary { op, left, right } => {
                let left = self.transpile_expression(left)?;
                let right = self.transpile_expression(right)?;
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    let tmp = self.fresh();
                    if *op == BinaryOp::And {
                        format!(
                            "{{ let {tmp} = {left}; if {tmp}.is_truthy() {{ {right} }} else {{ {tmp} }} }}"
                        )
                    } else {
                        format!(
                            "{{ let {tmp} = {left}; if {tmp}.is_truthy() {{ {tmp} }} else {{ {right} }} }}"
                        )
                    }
                } else {
                    self.checked(
                        expr,
                        format!("runtime::binary(&BinaryOp::{op:?}, {left}, {right})"),
                    )
                }
            }
            ExprKind::Unary { op, operand } => {
                let value = self.transpile_expression(operand)?;
                self.checked(expr, format!("runtime::unary(&UnaryOp::{op:?}, {value})"))
            }
            ExprKind::Call { callee, args } => {
                self.call(expr, callee, &args.iter().collect::<Vec<_>>())?
            }
            ExprKind::Pipeline { left, right } => {
                if let ExprKind::Call { callee, args } = &right.kind {
                    let mut all = vec![left.as_ref()];
                    all.extend(args.iter());
                    self.call(expr, callee, &all)?
                } else {
                    self.call(expr, right, &[left])?
                }
            }
            ExprKind::Lambda { params, body } => self.function("<lambda>", params, body)?,
            ExprKind::List(items) | ExprKind::Tuple(items) => {
                let items = items
                    .iter()
                    .map(|e| self.transpile_expression(e))
                    .collect::<RyndResult<Vec<_>>>()?
                    .join(", ");
                format!(
                    "Value::{}(vec![{items}])",
                    if matches!(expr.kind, ExprKind::List(_)) {
                        "list"
                    } else {
                        "tuple"
                    }
                )
            }
            ExprKind::Map(pairs) => {
                let mut code = vec![];
                for (key, value) in pairs {
                    let key = self.transpile_expression(key)?;
                    let value = self.transpile_expression(value)?;
                    code.push(format!("(runtime::map_key(&({key})), {value})"));
                }
                format!(
                    "Value::map(vec![{}].into_iter().collect())",
                    code.join(", ")
                )
            }
            ExprKind::Index { target, index } => {
                let target = self.transpile_expression(target)?;
                let index = self.transpile_expression(index)?;
                self.checked(expr, format!("runtime::index(&({target}), &({index}))"))
            }
            ExprKind::FieldAccess { target, field }
            | ExprKind::SafeFieldAccess { target, field } => {
                let target = self.transpile_expression(target)?;
                self.checked(
                    expr,
                    format!(
                        "runtime::field(&({target}), {field:?}, {})",
                        matches!(expr.kind, ExprKind::SafeFieldAccess { .. })
                    ),
                )
            }
            ExprKind::Elvis { left, right } => {
                let left = self.transpile_expression(left)?;
                let right = self.transpile_expression(right)?;
                let tmp = self.fresh();
                format!(
                    "{{ let {tmp} = {left}; if {tmp}.is_truthy() {{ {tmp} }} else {{ {right} }} }}"
                )
            }
            ExprKind::Range {
                start,
                end,
                inclusive,
            } => {
                let start = self.transpile_expression(start)?;
                let end = self.transpile_expression(end)?;
                self.checked(
                    expr,
                    format!("runtime::make_range(&({start}), &({end}), {inclusive})"),
                )
            }
            ExprKind::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let c = self.transpile_expression(condition)?;
                let t = self.transpile_expression(then_branch)?;
                let e = if let Some(e) = else_branch {
                    self.transpile_expression(e)?
                } else {
                    "Value::Nil".into()
                };
                format!("if ({c}).is_truthy() {{ {t} }} else {{ {e} }}")
            }
            ExprKind::Block {
                statements,
                final_expr,
            } => {
                let base = self.bindings.len();
                self.depth += 1;
                let mut code = String::from("{\n");
                for stmt in statements {
                    code.push_str(&self.statement(stmt)?);
                }
                code.push_str(&if let Some(e) = final_expr {
                    self.transpile_expression(e)?
                } else {
                    "Value::Nil".into()
                });
                code.push_str("\n}");
                self.bindings.truncate(base);
                self.depth -= 1;
                code
            }
            ExprKind::Match { target, arms } => {
                let label = self.fresh();
                let value = self.fresh();
                let target = self.transpile_expression(target)?;
                let mut code = format!("'{label}: {{ let {value} = {target};\n");
                for arm in arms {
                    let base = self.bindings.len();
                    self.depth += 1;
                    let bindings = self.fresh();
                    code.push_str(&format!(
                        "if let Some({bindings}) = runtime::match_pattern(&{}, &{value}) {{\n",
                        pattern_code(&arm.pattern)
                    ));
                    code.push_str(&self.bind_names(pattern_names(&arm.pattern), &bindings));
                    let guard = if let Some(g) = &arm.guard {
                        format!("({}).is_truthy()", self.transpile_expression(g)?)
                    } else {
                        "true".into()
                    };
                    let body = self.transpile_expression(&arm.body)?;
                    code.push_str(&format!("if {guard} {{ break '{label} {body}; }}\n}}\n"));
                    self.bindings.truncate(base);
                    self.depth -= 1;
                }
                code.push_str("Value::Nil\n}");
                code
            }
            ExprKind::Comprehension { .. } | ExprKind::MapComprehension { .. } => unreachable!(),
        })
    }
}
fn literal_code(lit: &Literal) -> String {
    match lit {
        Literal::Nil => "Literal::Nil".into(),
        Literal::Bool(v) => format!("Literal::Bool({v})"),
        Literal::Int(v) => format!("Literal::Int({v})"),
        Literal::Float(v) => format!("Literal::Float(f64::from_bits({}))", v.to_bits()),
        Literal::String(v) => format!("Literal::String({v:?}.into())"),
    }
}
fn pattern_code(pattern: &Pattern) -> String {
    match pattern {
        Pattern::Wildcard => "Pattern::Wildcard".into(),
        Pattern::Variable(name) => format!("Pattern::Variable({name:?}.into())"),
        Pattern::Literal(lit) => format!("Pattern::Literal({})", literal_code(lit)),
        Pattern::List(ps) | Pattern::Tuple(ps) => format!(
            "Pattern::{}(vec![{}])",
            if matches!(pattern, Pattern::List(_)) {
                "List"
            } else {
                "Tuple"
            },
            ps.iter().map(pattern_code).collect::<Vec<_>>().join(", ")
        ),
        Pattern::Variant { name, args } => format!(
            "Pattern::Variant {{ name: {name:?}.into(), args: vec![{}] }}",
            args.iter().map(pattern_code).collect::<Vec<_>>().join(", ")
        ),
    }
}

fn span_code(span: &crate::Span) -> String {
    let code = format!("Span::new({}, {})", span.line, span.column);
    match &span.file {
        Some(file) => format!("{code}.with_file({file:?})"),
        None => code,
    }
}
